### ISSUE TITLE
Class 'YubarajShrestha\NCHL\NchlServiceProvider' not found

### ISSUE THREAD

**Issue by pawandeltatech** [yubarajshrestha/nchl#16]
![Capture](https://user-images.githubusercontent.com/86183263/127347661-cc4debbf-b35e-45d7-8c3e-5fe43a6d4a47.PNG)

**Comment by yubarajshrestha** [comment]
@pawandeltatech It may be because of version upgrades. It's been long that I have worked on this package. If you continued working on this please don't forget to create PR. Thanks.
